### ISSUE TITLE
Incompatible with Babel 7 prerelease.

### ISSUE THREAD

**Issue by phyllisstein** [codemix/babel-plugin-closure-elimination#29]
This is for sure a low-priority issue, since Babel 7 is still in its alpha stages, but I thought I'd flag that this plugin will stop working after the version bump:

```
    ERROR in ./src/server.js
    Module build failed: TypeError: /Users/daniel/Repos/Ignota/rupertsberg/src/server.js: babel.traverse.clearCache is not a function
        at PluginPass.exit (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-plugin-closure-elimination/lib/index.js:132:26)
        at newFn (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-traverse/lib/visitors.js:236:21)
        at NodePath._call (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-traverse/lib/path/context.js:68:19)
        at NodePath.call (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-traverse/lib/path/context.js:42:17)
        at NodePath.visit (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-traverse/lib/path/context.js:112:8)
        at TraversalContext.visitQueue (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-traverse/lib/context.js:137:18)
        at TraversalContext.visitSingle (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-traverse/lib/context.js:96:19)
        at TraversalContext.visit (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-traverse/lib/context.js:178:19)
        at Function.traverse.node (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-traverse/lib/index.js:108:17)
        at traverse (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-traverse/lib/index.js:75:12)
        at File.transform (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-core/lib/transformation/file/index.js:495:35)
        at /Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-core/lib/transformation/pipeline.js:54:17
        at File.wrap (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-core/lib/transformation/file/index.js:514:14)
        at Object.transform (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-core/lib/transformation/pipeline.js:51:15)
        at transpile (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-loader/lib/index.js:50:20)
        at Object.module.exports (/Users/daniel/Repos/Ignota/rupertsberg/node_modules/babel-loader/lib/index.js:175:20)
     @ multi babel-polyfill ./server
```

Thanks for your work on this---can't wait to take it for a spin at some point. 😬

**Comment by kurtextrem** [comment]
Worth nothing is, versions under 1.2.0 work.

**Comment by phyllisstein** [comment]
Oh wow, right you are! v1.1.16 just compiled fine.

**Comment by hzoo** [comment]
We're in beta now, and it should be a simple fix if that's the only error. relevant pr is https://github.com/babel/babel/pull/4835/files

**Comment by phyllisstein** [comment]
Thanks @hzoo! It turned out to be this PR, but you set me on the right track 😄 : https://github.com/babel/babel/pull/5494. Will follow up with a PR here shortly.
